version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: bikeapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
